---
title: "suggestion_tries"
output: html_document
date: "2025-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Carl DeBoer suggested mashing datasets together and plotting a big PCA. I think I'll first try this with A1 and TE for LUAD.

# Multi-Dataset PCA (DeBoer's suggestion)

## Read in data
```{r}

## Read in the A1 normalized expression data
A1_exprs <- read.table("../../2_Outputs/2_Airway_expression/A1_exprs_20250403.txt", sep = " ")

## Read in the TE normalized expression data
TE_exprs <- read.table("../../2_Outputs/3_Tumor_expression/TE_data_20250403.txt", sep = " ")

```

## Combine datasets together
```{r}
TE_exprs_filtered <- TE_exprs %>%
  filter(Gene %in% A1_exprs$Gene)

A1_exprs_filtered <- A1_exprs %>%
  filter(Gene %in% TE_exprs_filtered$Gene)

A1_TE_exprs <- inner_join(A1_exprs, TE_exprs, by = "Gene")

## Note: I need to handle duplicate genes in the prev script
```


## Redoing the visualizations using normalization to better stratify samples in PCA and hierarchical clustering
```{r}
library(DESeq2)
library("pheatmap")
library("vsn")
library(gridExtra)
library(grid)

# Create a design matrix
groups <- rep(c("Tumor","Normal"), length(counts_matched_T_NM)/2)
design <- model.matrix(~0 + groups)

colData <- data.frame(sample = colnames(counts_matched_T_NM), row.names = colnames(counts_matched_T_NM), group = groups)

dds <- DESeqDataSetFromMatrix(countData = as.matrix(counts_matched_T_NM),
                              colData = colData,
                              design= design)



# Variance stabilizing transformations (VST) for visualization
vsd <- vst(dds, blind=FALSE)
#head(assay(vsd), 3)
plotPCA(vsd, intgroup=c("group"))

# Normalize and check variance
# this gives log2(n + 1)
ntd <- normTransform(dds)
meanSdPlot(assay(ntd))
meanSdPlot(assay(vsd))


# Heatmap of count matrix
dds <- estimateSizeFactors(dds)  # Estimates size factors for normalization
select <- order(rowMeans(counts(dds,normalized=TRUE)),
                decreasing=TRUE)[1:1000]

df <- as.data.frame(groups)
rownames(df) <- rownames(colData)

# Order columns based on group
ordered_cols <- order(colData$group)

# Heatmap
p <- pheatmap(assay(ntd)[select, ordered_cols], 
         cluster_rows=TRUE,
         cluster_cols=TRUE, 
         show_rownames=FALSE,
         show_colnames = TRUE,
         treeheight_row = 0,
         treeheight_col = 0,
         gaps_col = 1,
         annotation_col=df[ordered_cols, , drop=FALSE])

# TCGA-38-4626-01A still appears as an outlier in the heatmap even if that disappears in the PCA
# Note that the samples with suffix -01B cluster together and look quite different. These were FFPE. Potentially remove?

```




